import time
import sys

def jojo():
    #Emptiness
    print("\033[H\033[J")

def tim(job):
    #Animation
    jojo()
    print("0%[••••••••••••••••••••]")
    time.sleep(job)
    jojo()
    print("5%[#•••••••••••••••••••]")
    time.sleep(job)
    jojo()
    print("10%[##•••••••••••••••••]")
    time.sleep(job)
    jojo()
    print("15%[###••••••••••••••••]")
    time.sleep(job)
    jojo()
    print("21%[####•••••••••••••••]")
    time.sleep(job)
    jojo()
    print("26%[#####••••••••••••••]")
    time.sleep(job)
    jojo()
    print("31%[######•••••••••••••]")
    time.sleep(job)
    jojo()
    print("36%[#######••••••••••••]")
    time.sleep(job)
    jojo()
    print("42%[########•••••••••••]")
    time.sleep(job)
    jojo()
    print("47%[#########••••••••••]")
    time.sleep(job)
    jojo()
    print("52%[##########•••••••••]")
    time.sleep(job)
    jojo()
    print("57%[###########••••••••]")
    time.sleep(job)
    jojo()
    print("63%[############•••••••]")
    time.sleep(job)
    jojo()
    print("68%[#############••••••]")
    time.sleep(job)
    jojo()
    print("73%[##############•••••]")
    time.sleep(job)
    jojo()
    print("78%[###############••••]")
    time.sleep(job)
    jojo()
    print("84%[################•••]")
    time.sleep(job)
    jojo()
    print("89%[#################••]")
    time.sleep(job)
    jojo()
    print("94%[##################•]")
    time.sleep(job)
    jojo()
    print("100%[##################]")
    time.sleep(job)
    jojo()
    
def hook(hko, plot, n = None):
    if n is None:
        n = 0.1
    print(hko)
    for i in f"{plot}\n":
        time.sleep(n)
        sys.stdout.write(i)
        sys.stdout.flush()